# wrangler.toml
name = "lets-win-keno"
main = "src/index.js"
compatibility_date = "2025-06-17"
workers_dev = true

# wrangler.toml (wrangler v3.88.0^)
[observability.logs]
enabled = true

[vars]
# GITHUB_WEBHOOK_SECRET = "your-secret-value"
